version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # ตัวอย่างการ mount โฟลเดอร์ปัจจุบันเข้าไปใน /usr/share/nginx/html
      - .:/usr/share/nginx/html
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_app_db
    # สามารถเพิ่ม volumes สำหรับเก็บข้อมูลถาวรได้ แต่ในที่นี้เน้นแค่ Environment
    restart: always
