name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Lint YAML Files (Check Syntax)
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: |
          .github/workflows/ci.yml
          docker-compose.yml
          k8s/deployment.yml
          k8s/service.yml
        config_file: .yamllint.yml
        strict: false

    - name: Check Docker Compose Syntax
      run: |
        echo "Validating Docker Compose configuration..."
        # Use docker compose (v2) instead of docker-compose
        docker compose config --quiet
        echo "Docker Compose validation successful!"

    - name: Install and Setup Kubectl
      run: |
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Kubernetes YAML Validation
      run: |
        echo "Validating Kubernetes manifests syntax..."
        # Just validate YAML syntax without cluster connection
        for file in k8s/*.yml; do
          echo "Checking $file..."
          kubectl apply -f "$file" --dry-run=client --validate=false -o yaml > /dev/null 2>&1 || {
            echo "Error: Invalid YAML syntax in $file"
            exit 1
          }
        done
        echo "All Kubernetes YAML files have valid syntax!"

    - name: Validate All YAML Files Structure
      run: |
        echo "Running additional YAML structure validation..."
        # Check if all required files exist
        if [ ! -f "docker-compose.yml" ]; then
          echo "Error: docker-compose.yml not found"
          exit 1
        fi
        if [ ! -f "k8s/deployment.yml" ]; then
          echo "Error: k8s/deployment.yml not found"
          exit 1
        fi
        if [ ! -f "k8s/service.yml" ]; then
          echo "Error: k8s/service.yml not found"
          exit 1
        fi
        echo "All required YAML files are present!"
        
        # Validate Docker Compose has required services
        if ! docker compose config | grep -q "services:"; then
          echo "Error: No services found in docker-compose.yml"
          exit 1
        fi
        echo "Docker Compose structure validation passed!"

    - name: Build Application (Example)
      run: echo "Build successful for $(git rev-parse --short HEAD)"

    - name: Notify Workflow Finished
      run: echo "CI/CD Workflow finished successfully."
